#Direct the main healthcheck to port 8000
#Direct the face-bokeh to port 8001
#Direct the face-emotion to port 8002
version: "3"

services:
  health:
    build: ./
    restart: always
    ports:
      - 8000:8000

  bokeh:
    build: ./face-bokeh
    restart: always
    ports:
      - 8001:8001
    depends_on: 
      - health
  
  emotion:
    build: ./face-emotion
    restart: always
    ports:
      - 8002:8002
    depends_on: 
      - health
  